version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errorlint
    - bodyclose
    - bidichk
    - misspell
    - unconvert
    - prealloc
    - predeclared
    - nolintlint
    - unparam

formatters:
  enable:
    - gofumpt

issues:
  exclude-use-default: false
